from django.urls import path

from .views import (
    ProfileView,
    ProfileDelete,
    ProfileUpdateView,
    EquipmentModelView,
    EquipmentModelDetail,
    EquipmentModelCreate,
    EquipmentModelDelete,
    EquipmentModelUpdate,
    EngineModelView,
    EngineModelDelete,
    EngineModelCreate,
    EngineModelDetail,
    EngineModelUpdate,
    TransmissionModelView,
    TransmissionModelDetail,
    TransmissionModelCreate,
    TransmissionModelUpdate,
    TransmissionModelDelete,
    DrivingAxleModelView,
    DrivingAxleModelDetail,
    DrivingAxleModelCreate,
    DrivingAxleModelUpdate,
    DrivingAxleModelDelete,
    ControlAxleModelView,
    ControlAxleModelDetail,
    ControlAxleModelUpdate,
    ControlAxleModelCreate,
    ControlAxleModelDelete,
    ServiceTypeDetail,
    ServiceTypeView,
    ServiceTypeCreate,
    ServiceTypeDelete,
    ServiceTypeUpdate,
    ServiceCompanyView,
    ServiceCompanyDetail,
    ServiceCompanyDelete,
    ServiceCompanyUpdate,
    ServiceCompanyCreate,
    RepairMethodView,
    RepairMethodDetail,
    RepairMethodCreate,
    RepairMethodDelete,
    RepairMethodUpdate,
    WorkoffNodeView,
    WorkoffNodeDetail,
    WorkoffNodeCreate,
    WorkoffNodeDelete,
    WorkoffNodeUpdate
)


urlpatterns = [
    #profiles
    path('profiles/', ProfileView.as_view(), name='profiles'),
    path('profiles/<int:pk>/delete/', ProfileDelete.as_view(), name='profile_delete'),
    path('profiles/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile_update'),
    #EquipmentModels
    path('equipment_models', EquipmentModelView.as_view(), name='equipment_models'),
    path('equipment_models/<int:pk>', EquipmentModelDetail.as_view(), name='equipment_model_detail'),
    path('equipment_models/<int:pk>/delete/', EquipmentModelDelete.as_view(), name='equipment_model_delete'),
    path('equipment_models/<int:pk>/update/', EquipmentModelUpdate.as_view(), name='equipment_model_update'),
    path('equipment_models/create', EquipmentModelCreate.as_view(), name='equipment_model_create'),
    #EngineModels
    path('engine_models', EngineModelView.as_view(), name='engine_models'),
    path('engine_models/<int:pk>', EngineModelDetail.as_view(), name='engine_model_detail'),
    path('engine_models/<int:pk>/delete/', EngineModelDelete.as_view(), name='engine_model_delete'),
    path('engine_models/<int:pk>/update/', EngineModelUpdate.as_view(), name='engine_model_update'),
    path('engine_models/create', EngineModelCreate.as_view(), name='engine_model_create'),
    # TransmissionModel
    path('transmission_models', TransmissionModelView.as_view(), name='transmission_models'),
    path('transmission_models/<int:pk>', TransmissionModelDetail.as_view(), name='transmission_model_detail'),
    path('transmission_models/<int:pk>/delete/', TransmissionModelDelete.as_view(), name='transmission_model_delete'),
    path('transmission_models/<int:pk>/update/', TransmissionModelUpdate.as_view(), name='transmission_model_update'),
    path('transmission_models/create', TransmissionModelCreate.as_view(), name='transmission_model_create'),
    # DrivingAxleModel
    path('driving_axle_models', DrivingAxleModelView.as_view(), name='driving_axle_models'),
    path('driving_axle_models/<int:pk>', DrivingAxleModelDetail.as_view(), name='driving_axle_model_detail'),
    path('driving_axle_models/<int:pk>/delete/', DrivingAxleModelDelete.as_view(), name='driving_axle_model_delete'),
    path('driving_axle_models/<int:pk>/update/', DrivingAxleModelUpdate.as_view(), name='driving_axle_model_update'),
    path('driving_axle_models/create', DrivingAxleModelCreate.as_view(), name='driving_axle_model_create'),
    # ControlAxleModel
    path('control_axle_models', ControlAxleModelView.as_view(), name='control_axle_models'),
    path('control_axle_models/<int:pk>', ControlAxleModelDetail.as_view(), name='control_axle_model_detail'),
    path('control_axle_models/<int:pk>/delete/', ControlAxleModelDelete.as_view(), name='control_axle_model_delete'),
    path('control_axle_models/<int:pk>/update/', ControlAxleModelUpdate.as_view(), name='control_axle_model_update'),
    path('control_axle_models/create', ControlAxleModelCreate.as_view(), name='control_axle_model_create'),
    # ServiceType
    path('service_types', ServiceTypeView.as_view(), name='service_types'),
    path('service_types/<int:pk>', ServiceTypeDetail.as_view(), name='service_type_detail'),
    path('service_types/<int:pk>/delete/', ServiceTypeDelete.as_view(), name='service_type_delete'),
    path('service_types/<int:pk>/update/', ServiceTypeUpdate.as_view(), name='service_type_update'),
    path('service_types/create', ServiceTypeCreate.as_view(), name='service_type_create'),
    # ServiceCompany
    path('service_companies', ServiceCompanyView.as_view(), name='service_companies'),
    path('service_companies/<int:pk>', ServiceCompanyDetail.as_view(), name='service_company_detail'),
    path('service_companies/<int:pk>/delete/', ServiceCompanyDelete.as_view(), name='service_company_delete'),
    path('service_companies/<int:pk>/update/', ServiceCompanyUpdate.as_view(), name='service_company_update'),
    path('service_companies/create', ServiceCompanyCreate.as_view(), name='service_company_create'),
    # RepairMethod
    path('repair_methods', RepairMethodView.as_view(), name='repair_methods'),
    path('repair_methods/<int:pk>', RepairMethodDetail.as_view(), name='repair_method_detail'),
    path('repair_methods/<int:pk>/delete/', RepairMethodDelete.as_view(), name='repair_method_delete'),
    path('repair_methods/<int:pk>/update/', RepairMethodUpdate.as_view(), name='repair_method_update'),
    path('repair_methods/create', RepairMethodCreate.as_view(), name='repair_method_create'),
    # WorkoffNodes
    path('workoff_nodes', WorkoffNodeView.as_view(), name='workoff_nodes'),
    path('workoff_nodes/<int:pk>', WorkoffNodeDetail.as_view(), name='workoff_node_detail'),
    path('workoff_nodes/<int:pk>/delete/', WorkoffNodeDelete.as_view(), name='workoff_node_delete'),
    path('workoff_nodes/<int:pk>/update/', WorkoffNodeUpdate.as_view(), name='workoff_node_update'),
    path('workoff_nodes/create', WorkoffNodeCreate.as_view(), name='workoff_node_create'),
]
