# Generated by Django 5.0.6 on 2024-07-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_service', '0002_servicecompany_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='options',
            field=models.TextField(blank=True),
        ),
    ]
