# Generated by Django 5.0.6 on 2024-07-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loader_service', '0003_machine_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='dead_time',
            field=models.IntegerField(blank=True),
        ),
    ]
